travis:
  secure:
    BINSTAR_TOKEN: aiCAS3eT1J2Oj3Ckzbxld5oEtH5gcib8S9D1A+p0DMj16wT1911dxLoesY2dVsVp66zgcqBUyKeCcjrFWzN+IOcWQQhBzsvXYwQ5gfA11I4YmJNH3/nprwGRLTR/l2ohxY9ukbd4k0Pa0cBj/MPjwo1ffRH8OMLcYuJgs5B7ppq8Avbt3icPd99EToEVStk9cDmCh9PLlTMhyUL/+FG+DGs5N7IFHepmQVTMrOFd1LIaJMKmS+qn+Eb7GccJYnOFXJCbUfF4ZuIrsHIgGzomasztcGtKn2RyatOimVNLMplKnQXSniq8FVomA1tnmwml/MLCWD3GJ/Gw5XpEGV0fIgeyW6FQM31pH0INOsEPtSMnxlvU0yFrqzWq7dwuqu9ENCEmw4et4hcyMKkYUYxRC9FinZDJQHnUgQoML8Gi0aRfgwSRvv4BIaV8bqvN3oZokgEC/YCCWFf/YvsIfucSa4QO4INtgSu1enFbmxBkwOMnO8UahozF5Y+dPxpnrXJxgsPLTBuUqiKih5VLcdJm5HOhMVUoiC8S8wQinYvxFOmawS9sBdfGNNNddTpzdQqb4aIeVf5Qmcm7a98Z29llSgd9oZu1eno13+KAQGUxtJcTPDCwE9KOI9djqpfA085l8r9Xjy8UPE8ynQFTVg05/5QZNOfETNl4+5SyEGoSN7Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
